input = """
% Instantiation generated by
% DLV [build BEN/Oct 14 2010   gcc 4.4.3]

% EDB facts:
start(1).
arc(0,1).
arc(0,2).
arc(0,3).
arc(0,7).
arc(0,8).
arc(1,0).
arc(1,3).
arc(1,6).
arc(1,9).
arc(2,0).
arc(2,3).
arc(2,4).
arc(2,7).
arc(2,8).
arc(2,9).
arc(3,0).
arc(3,1).
arc(3,2).
arc(3,9).
arc(4,2).
arc(4,5).
arc(4,6).
arc(4,9).
arc(5,4).
arc(5,6).
arc(5,9).
arc(6,1).
arc(6,4).
arc(6,5).
arc(6,9).
arc(7,0).
arc(7,2).
arc(7,8).
arc(8,0).
arc(8,2).
arc(8,7).
arc(9,1).
arc(9,2).
arc(9,3).
arc(9,4).
arc(9,5).
arc(9,6).
vertex(0).
vertex(1).
vertex(2).
vertex(3).
vertex(4).
vertex(5).
vertex(6).
vertex(7).
vertex(8).
vertex(9).
% Residual ground instantiation of the program:
in_hm(0,1) v out_hm(0,1).
in_hm(0,2) v out_hm(0,2).
in_hm(0,3) v out_hm(0,3).
in_hm(0,7) v out_hm(0,7).
in_hm(0,8) v out_hm(0,8).
in_hm(1,0) v out_hm(1,0).
in_hm(1,3) v out_hm(1,3).
in_hm(1,6) v out_hm(1,6).
in_hm(1,9) v out_hm(1,9).
in_hm(2,0) v out_hm(2,0).
in_hm(2,3) v out_hm(2,3).
in_hm(2,4) v out_hm(2,4).
in_hm(2,7) v out_hm(2,7).
in_hm(2,8) v out_hm(2,8).
in_hm(2,9) v out_hm(2,9).
in_hm(3,0) v out_hm(3,0).
in_hm(3,1) v out_hm(3,1).
in_hm(3,2) v out_hm(3,2).
in_hm(3,9) v out_hm(3,9).
in_hm(4,2) v out_hm(4,2).
in_hm(4,5) v out_hm(4,5).
in_hm(4,6) v out_hm(4,6).
in_hm(4,9) v out_hm(4,9).
in_hm(5,4) v out_hm(5,4).
in_hm(5,6) v out_hm(5,6).
in_hm(5,9) v out_hm(5,9).
in_hm(6,1) v out_hm(6,1).
in_hm(6,4) v out_hm(6,4).
in_hm(6,5) v out_hm(6,5).
in_hm(6,9) v out_hm(6,9).
in_hm(7,0) v out_hm(7,0).
in_hm(7,2) v out_hm(7,2).
in_hm(7,8) v out_hm(7,8).
in_hm(8,0) v out_hm(8,0).
in_hm(8,2) v out_hm(8,2).
in_hm(8,7) v out_hm(8,7).
in_hm(9,1) v out_hm(9,1).
in_hm(9,2) v out_hm(9,2).
in_hm(9,3) v out_hm(9,3).
in_hm(9,4) v out_hm(9,4).
in_hm(9,5) v out_hm(9,5).
in_hm(9,6) v out_hm(9,6).
reached(0) :- in_hm(1,0).
reached(9) :- in_hm(1,9).
reached(6) :- in_hm(1,6).
reached(3) :- in_hm(1,3).
reached(1) :- reached(0), in_hm(0,1).
reached(8) :- reached(0), in_hm(0,8).
reached(7) :- reached(0), in_hm(0,7).
reached(3) :- reached(0), in_hm(0,3).
reached(2) :- reached(0), in_hm(0,2).
reached(1) :- reached(3), in_hm(3,1).
reached(2) :- reached(3), in_hm(3,2).
reached(9) :- reached(3), in_hm(3,9).
reached(0) :- reached(3), in_hm(3,0).
reached(1) :- reached(6), in_hm(6,1).
reached(9) :- reached(6), in_hm(6,9).
reached(5) :- reached(6), in_hm(6,5).
reached(4) :- reached(6), in_hm(6,4).
reached(1) :- reached(9), in_hm(9,1).
reached(6) :- reached(9), in_hm(9,6).
reached(5) :- reached(9), in_hm(9,5).
reached(4) :- reached(9), in_hm(9,4).
reached(3) :- reached(9), in_hm(9,3).
reached(2) :- reached(9), in_hm(9,2).
reached(0) :- reached(1), in_hm(1,0).
reached(9) :- reached(1), in_hm(1,9).
reached(6) :- reached(1), in_hm(1,6).
reached(3) :- reached(1), in_hm(1,3).
reached(0) :- reached(2), in_hm(2,0).
reached(4) :- reached(2), in_hm(2,4).
reached(7) :- reached(2), in_hm(2,7).
reached(8) :- reached(2), in_hm(2,8).
reached(9) :- reached(2), in_hm(2,9).
reached(3) :- reached(2), in_hm(2,3).
reached(5) :- reached(4), in_hm(4,5).
reached(6) :- reached(4), in_hm(4,6).
reached(9) :- reached(4), in_hm(4,9).
reached(2) :- reached(4), in_hm(4,2).
reached(4) :- reached(5), in_hm(5,4).
reached(9) :- reached(5), in_hm(5,9).
reached(6) :- reached(5), in_hm(5,6).
reached(0) :- reached(7), in_hm(7,0).
reached(8) :- reached(7), in_hm(7,8).
reached(2) :- reached(7), in_hm(7,2).
reached(0) :- reached(8), in_hm(8,0).
reached(7) :- reached(8), in_hm(8,7).
reached(2) :- reached(8), in_hm(8,2).
:- in_hm(0,1), in_hm(0,8).
:- in_hm(0,1), in_hm(0,7).
:- in_hm(0,1), in_hm(0,3).
:- in_hm(0,1), in_hm(0,2).
:- in_hm(0,2), in_hm(0,1).
:- in_hm(0,2), in_hm(0,8).
:- in_hm(0,2), in_hm(0,7).
:- in_hm(0,2), in_hm(0,3).
:- in_hm(0,3), in_hm(0,1).
:- in_hm(0,3), in_hm(0,8).
:- in_hm(0,3), in_hm(0,7).
:- in_hm(0,3), in_hm(0,2).
:- in_hm(0,7), in_hm(0,1).
:- in_hm(0,7), in_hm(0,8).
:- in_hm(0,7), in_hm(0,3).
:- in_hm(0,7), in_hm(0,2).
:- in_hm(0,8), in_hm(0,1).
:- in_hm(0,8), in_hm(0,7).
:- in_hm(0,8), in_hm(0,3).
:- in_hm(0,8), in_hm(0,2).
:- in_hm(1,0), in_hm(1,9).
:- in_hm(1,0), in_hm(1,6).
:- in_hm(1,0), in_hm(1,3).
:- in_hm(1,3), in_hm(1,0).
:- in_hm(1,3), in_hm(1,9).
:- in_hm(1,3), in_hm(1,6).
:- in_hm(1,6), in_hm(1,0).
:- in_hm(1,6), in_hm(1,9).
:- in_hm(1,6), in_hm(1,3).
:- in_hm(1,9), in_hm(1,0).
:- in_hm(1,9), in_hm(1,6).
:- in_hm(1,9), in_hm(1,3).
:- in_hm(2,0), in_hm(2,4).
:- in_hm(2,0), in_hm(2,7).
:- in_hm(2,0), in_hm(2,8).
:- in_hm(2,0), in_hm(2,9).
:- in_hm(2,0), in_hm(2,3).
:- in_hm(2,3), in_hm(2,0).
:- in_hm(2,3), in_hm(2,4).
:- in_hm(2,3), in_hm(2,7).
:- in_hm(2,3), in_hm(2,8).
:- in_hm(2,3), in_hm(2,9).
:- in_hm(2,4), in_hm(2,0).
:- in_hm(2,4), in_hm(2,7).
:- in_hm(2,4), in_hm(2,8).
:- in_hm(2,4), in_hm(2,9).
:- in_hm(2,4), in_hm(2,3).
:- in_hm(2,7), in_hm(2,0).
:- in_hm(2,7), in_hm(2,4).
:- in_hm(2,7), in_hm(2,8).
:- in_hm(2,7), in_hm(2,9).
:- in_hm(2,7), in_hm(2,3).
:- in_hm(2,8), in_hm(2,0).
:- in_hm(2,8), in_hm(2,4).
:- in_hm(2,8), in_hm(2,7).
:- in_hm(2,8), in_hm(2,9).
:- in_hm(2,8), in_hm(2,3).
:- in_hm(2,9), in_hm(2,0).
:- in_hm(2,9), in_hm(2,4).
:- in_hm(2,9), in_hm(2,7).
:- in_hm(2,9), in_hm(2,8).
:- in_hm(2,9), in_hm(2,3).
:- in_hm(3,0), in_hm(3,1).
:- in_hm(3,0), in_hm(3,2).
:- in_hm(3,0), in_hm(3,9).
:- in_hm(3,1), in_hm(3,2).
:- in_hm(3,1), in_hm(3,9).
:- in_hm(3,1), in_hm(3,0).
:- in_hm(3,2), in_hm(3,1).
:- in_hm(3,2), in_hm(3,9).
:- in_hm(3,2), in_hm(3,0).
:- in_hm(3,9), in_hm(3,1).
:- in_hm(3,9), in_hm(3,2).
:- in_hm(3,9), in_hm(3,0).
:- in_hm(4,2), in_hm(4,5).
:- in_hm(4,2), in_hm(4,6).
:- in_hm(4,2), in_hm(4,9).
:- in_hm(4,5), in_hm(4,6).
:- in_hm(4,5), in_hm(4,9).
:- in_hm(4,5), in_hm(4,2).
:- in_hm(4,6), in_hm(4,5).
:- in_hm(4,6), in_hm(4,9).
:- in_hm(4,6), in_hm(4,2).
:- in_hm(4,9), in_hm(4,5).
:- in_hm(4,9), in_hm(4,6).
:- in_hm(4,9), in_hm(4,2).
:- in_hm(5,4), in_hm(5,9).
:- in_hm(5,4), in_hm(5,6).
:- in_hm(5,6), in_hm(5,4).
:- in_hm(5,6), in_hm(5,9).
:- in_hm(5,9), in_hm(5,4).
:- in_hm(5,9), in_hm(5,6).
:- in_hm(6,1), in_hm(6,9).
:- in_hm(6,1), in_hm(6,5).
:- in_hm(6,1), in_hm(6,4).
:- in_hm(6,4), in_hm(6,1).
:- in_hm(6,4), in_hm(6,9).
:- in_hm(6,4), in_hm(6,5).
:- in_hm(6,5), in_hm(6,1).
:- in_hm(6,5), in_hm(6,9).
:- in_hm(6,5), in_hm(6,4).
:- in_hm(6,9), in_hm(6,1).
:- in_hm(6,9), in_hm(6,5).
:- in_hm(6,9), in_hm(6,4).
:- in_hm(7,0), in_hm(7,8).
:- in_hm(7,0), in_hm(7,2).
:- in_hm(7,2), in_hm(7,0).
:- in_hm(7,2), in_hm(7,8).
:- in_hm(7,8), in_hm(7,0).
:- in_hm(7,8), in_hm(7,2).
:- in_hm(8,0), in_hm(8,7).
:- in_hm(8,0), in_hm(8,2).
:- in_hm(8,2), in_hm(8,0).
:- in_hm(8,2), in_hm(8,7).
:- in_hm(8,7), in_hm(8,0).
:- in_hm(8,7), in_hm(8,2).
:- in_hm(9,1), in_hm(9,6).
:- in_hm(9,1), in_hm(9,5).
:- in_hm(9,1), in_hm(9,4).
:- in_hm(9,1), in_hm(9,3).
:- in_hm(9,1), in_hm(9,2).
:- in_hm(9,2), in_hm(9,1).
:- in_hm(9,2), in_hm(9,6).
:- in_hm(9,2), in_hm(9,5).
:- in_hm(9,2), in_hm(9,4).
:- in_hm(9,2), in_hm(9,3).
:- in_hm(9,3), in_hm(9,1).
:- in_hm(9,3), in_hm(9,6).
:- in_hm(9,3), in_hm(9,5).
:- in_hm(9,3), in_hm(9,4).
:- in_hm(9,3), in_hm(9,2).
:- in_hm(9,4), in_hm(9,1).
:- in_hm(9,4), in_hm(9,6).
:- in_hm(9,4), in_hm(9,5).
:- in_hm(9,4), in_hm(9,3).
:- in_hm(9,4), in_hm(9,2).
:- in_hm(9,5), in_hm(9,1).
:- in_hm(9,5), in_hm(9,6).
:- in_hm(9,5), in_hm(9,4).
:- in_hm(9,5), in_hm(9,3).
:- in_hm(9,5), in_hm(9,2).
:- in_hm(9,6), in_hm(9,1).
:- in_hm(9,6), in_hm(9,5).
:- in_hm(9,6), in_hm(9,4).
:- in_hm(9,6), in_hm(9,3).
:- in_hm(9,6), in_hm(9,2).
:- in_hm(0,1), in_hm(3,1).
:- in_hm(0,1), in_hm(9,1).
:- in_hm(0,1), in_hm(6,1).
:- in_hm(0,2), in_hm(3,2).
:- in_hm(0,2), in_hm(9,2).
:- in_hm(0,2), in_hm(8,2).
:- in_hm(0,2), in_hm(7,2).
:- in_hm(0,2), in_hm(4,2).
:- in_hm(0,3), in_hm(9,3).
:- in_hm(0,3), in_hm(2,3).
:- in_hm(0,3), in_hm(1,3).
:- in_hm(0,7), in_hm(2,7).
:- in_hm(0,7), in_hm(8,7).
:- in_hm(0,8), in_hm(2,8).
:- in_hm(0,8), in_hm(7,8).
:- in_hm(1,0), in_hm(8,0).
:- in_hm(1,0), in_hm(7,0).
:- in_hm(1,0), in_hm(3,0).
:- in_hm(1,0), in_hm(2,0).
:- in_hm(1,3), in_hm(0,3).
:- in_hm(1,3), in_hm(9,3).
:- in_hm(1,3), in_hm(2,3).
:- in_hm(1,6), in_hm(4,6).
:- in_hm(1,6), in_hm(9,6).
:- in_hm(1,6), in_hm(5,6).
:- in_hm(1,9), in_hm(2,9).
:- in_hm(1,9), in_hm(6,9).
:- in_hm(1,9), in_hm(5,9).
:- in_hm(1,9), in_hm(3,9).
:- in_hm(1,9), in_hm(4,9).
:- in_hm(2,0), in_hm(1,0).
:- in_hm(2,0), in_hm(8,0).
:- in_hm(2,0), in_hm(7,0).
:- in_hm(2,0), in_hm(3,0).
:- in_hm(2,3), in_hm(0,3).
:- in_hm(2,3), in_hm(9,3).
:- in_hm(2,3), in_hm(1,3).
:- in_hm(2,4), in_hm(9,4).
:- in_hm(2,4), in_hm(6,4).
:- in_hm(2,4), in_hm(5,4).
:- in_hm(2,7), in_hm(8,7).
:- in_hm(2,7), in_hm(0,7).
:- in_hm(2,8), in_hm(7,8).
:- in_hm(2,8), in_hm(0,8).
:- in_hm(2,9), in_hm(6,9).
:- in_hm(2,9), in_hm(5,9).
:- in_hm(2,9), in_hm(3,9).
:- in_hm(2,9), in_hm(4,9).
:- in_hm(2,9), in_hm(1,9).
:- in_hm(3,0), in_hm(1,0).
:- in_hm(3,0), in_hm(8,0).
:- in_hm(3,0), in_hm(7,0).
:- in_hm(3,0), in_hm(2,0).
:- in_hm(3,1), in_hm(9,1).
:- in_hm(3,1), in_hm(6,1).
:- in_hm(3,1), in_hm(0,1).
:- in_hm(3,2), in_hm(9,2).
:- in_hm(3,2), in_hm(8,2).
:- in_hm(3,2), in_hm(7,2).
:- in_hm(3,2), in_hm(4,2).
:- in_hm(3,2), in_hm(0,2).
:- in_hm(3,9), in_hm(2,9).
:- in_hm(3,9), in_hm(6,9).
:- in_hm(3,9), in_hm(5,9).
:- in_hm(3,9), in_hm(4,9).
:- in_hm(3,9), in_hm(1,9).
:- in_hm(4,2), in_hm(3,2).
:- in_hm(4,2), in_hm(9,2).
:- in_hm(4,2), in_hm(8,2).
:- in_hm(4,2), in_hm(7,2).
:- in_hm(4,2), in_hm(0,2).
:- in_hm(4,5), in_hm(9,5).
:- in_hm(4,5), in_hm(6,5).
:- in_hm(4,6), in_hm(9,6).
:- in_hm(4,6), in_hm(5,6).
:- in_hm(4,6), in_hm(1,6).
:- in_hm(4,9), in_hm(2,9).
:- in_hm(4,9), in_hm(6,9).
:- in_hm(4,9), in_hm(5,9).
:- in_hm(4,9), in_hm(3,9).
:- in_hm(4,9), in_hm(1,9).
:- in_hm(5,4), in_hm(2,4).
:- in_hm(5,4), in_hm(9,4).
:- in_hm(5,4), in_hm(6,4).
:- in_hm(5,6), in_hm(4,6).
:- in_hm(5,6), in_hm(9,6).
:- in_hm(5,6), in_hm(1,6).
:- in_hm(5,9), in_hm(2,9).
:- in_hm(5,9), in_hm(6,9).
:- in_hm(5,9), in_hm(3,9).
:- in_hm(5,9), in_hm(4,9).
:- in_hm(5,9), in_hm(1,9).
:- in_hm(6,1), in_hm(3,1).
:- in_hm(6,1), in_hm(9,1).
:- in_hm(6,1), in_hm(0,1).
:- in_hm(6,4), in_hm(2,4).
:- in_hm(6,4), in_hm(9,4).
:- in_hm(6,4), in_hm(5,4).
:- in_hm(6,5), in_hm(4,5).
:- in_hm(6,5), in_hm(9,5).
:- in_hm(6,9), in_hm(2,9).
:- in_hm(6,9), in_hm(5,9).
:- in_hm(6,9), in_hm(3,9).
:- in_hm(6,9), in_hm(4,9).
:- in_hm(6,9), in_hm(1,9).
:- in_hm(7,0), in_hm(1,0).
:- in_hm(7,0), in_hm(8,0).
:- in_hm(7,0), in_hm(3,0).
:- in_hm(7,0), in_hm(2,0).
:- in_hm(7,2), in_hm(3,2).
:- in_hm(7,2), in_hm(9,2).
:- in_hm(7,2), in_hm(8,2).
:- in_hm(7,2), in_hm(4,2).
:- in_hm(7,2), in_hm(0,2).
:- in_hm(7,8), in_hm(2,8).
:- in_hm(7,8), in_hm(0,8).
:- in_hm(8,0), in_hm(1,0).
:- in_hm(8,0), in_hm(7,0).
:- in_hm(8,0), in_hm(3,0).
:- in_hm(8,0), in_hm(2,0).
:- in_hm(8,2), in_hm(3,2).
:- in_hm(8,2), in_hm(9,2).
:- in_hm(8,2), in_hm(7,2).
:- in_hm(8,2), in_hm(4,2).
:- in_hm(8,2), in_hm(0,2).
:- in_hm(8,7), in_hm(2,7).
:- in_hm(8,7), in_hm(0,7).
:- in_hm(9,1), in_hm(3,1).
:- in_hm(9,1), in_hm(6,1).
:- in_hm(9,1), in_hm(0,1).
:- in_hm(9,2), in_hm(3,2).
:- in_hm(9,2), in_hm(8,2).
:- in_hm(9,2), in_hm(7,2).
:- in_hm(9,2), in_hm(4,2).
:- in_hm(9,2), in_hm(0,2).
:- in_hm(9,3), in_hm(0,3).
:- in_hm(9,3), in_hm(2,3).
:- in_hm(9,3), in_hm(1,3).
:- in_hm(9,4), in_hm(2,4).
:- in_hm(9,4), in_hm(6,4).
:- in_hm(9,4), in_hm(5,4).
:- in_hm(9,5), in_hm(4,5).
:- in_hm(9,5), in_hm(6,5).
:- in_hm(9,6), in_hm(4,6).
:- in_hm(9,6), in_hm(5,6).
:- in_hm(9,6), in_hm(1,6).
:- not reached(0).
:- not reached(0).
:- not reached(0).
:- not reached(0).
:- not reached(0).
:- not reached(1).
:- not reached(1).
:- not reached(1).
:- not reached(1).
:- not reached(2).
:- not reached(2).
:- not reached(2).
:- not reached(2).
:- not reached(2).
:- not reached(2).
:- not reached(3).
:- not reached(3).
:- not reached(3).
:- not reached(3).
:- not reached(4).
:- not reached(4).
:- not reached(4).
:- not reached(4).
:- not reached(5).
:- not reached(5).
:- not reached(5).
:- not reached(6).
:- not reached(6).
:- not reached(6).
:- not reached(6).
:- not reached(7).
:- not reached(7).
:- not reached(7).
:- not reached(8).
:- not reached(8).
:- not reached(8).
:- not reached(9).
:- not reached(9).
:- not reached(9).
:- not reached(9).
:- not reached(9).
:- not reached(9).

"""

output = """
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,1), in_hm(1,3), in_hm(2,7), in_hm(3,9), in_hm(4,2), in_hm(5,4), in_hm(6,5), in_hm(7,8), in_hm(8,0), in_hm(9,6), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,2), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,6), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,2), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,5), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,1), in_hm(1,3), in_hm(2,7), in_hm(3,9), in_hm(4,2), in_hm(5,6), in_hm(6,4), in_hm(7,8), in_hm(8,0), in_hm(9,5), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,2), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,1), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,2), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,1), in_hm(1,3), in_hm(2,8), in_hm(3,9), in_hm(4,2), in_hm(5,4), in_hm(6,5), in_hm(7,0), in_hm(8,7), in_hm(9,6), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,2), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,6), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,2), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,5), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,1), in_hm(1,3), in_hm(2,8), in_hm(3,9), in_hm(4,2), in_hm(5,6), in_hm(6,4), in_hm(7,0), in_hm(8,7), in_hm(9,5), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,2), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,1), out_hm(6,5), out_hm(6,9), out_hm(7,2), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,1), in_hm(1,6), in_hm(2,7), in_hm(3,2), in_hm(4,5), in_hm(5,9), in_hm(6,4), in_hm(7,8), in_hm(8,0), in_hm(9,3), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,6), out_hm(6,1), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,2), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,1), in_hm(1,6), in_hm(2,7), in_hm(3,2), in_hm(4,9), in_hm(5,4), in_hm(6,5), in_hm(7,8), in_hm(8,0), in_hm(9,3), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,9), out_hm(4,2), out_hm(4,5), out_hm(4,6), out_hm(5,6), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,2), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,1), in_hm(1,6), in_hm(2,8), in_hm(3,2), in_hm(4,5), in_hm(5,9), in_hm(6,4), in_hm(7,0), in_hm(8,7), in_hm(9,3), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,6), out_hm(6,1), out_hm(6,5), out_hm(6,9), out_hm(7,2), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,1), in_hm(1,6), in_hm(2,8), in_hm(3,2), in_hm(4,9), in_hm(5,4), in_hm(6,5), in_hm(7,0), in_hm(8,7), in_hm(9,3), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,9), out_hm(4,2), out_hm(4,5), out_hm(4,6), out_hm(5,6), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,2), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,6), in_hm(2,7), in_hm(3,1), in_hm(4,2), in_hm(5,4), in_hm(6,9), in_hm(7,8), in_hm(8,0), in_hm(9,5), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,6), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,5), out_hm(7,0), out_hm(7,2), out_hm(8,2), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,6), in_hm(2,7), in_hm(3,1), in_hm(4,2), in_hm(5,9), in_hm(6,5), in_hm(7,8), in_hm(8,0), in_hm(9,4), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,6), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,2), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,6), in_hm(2,7), in_hm(3,1), in_hm(4,5), in_hm(5,9), in_hm(6,4), in_hm(7,8), in_hm(8,0), in_hm(9,2), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,6), out_hm(6,1), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,2), out_hm(8,7), out_hm(9,1), out_hm(9,3), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,6), in_hm(2,7), in_hm(3,1), in_hm(4,9), in_hm(5,4), in_hm(6,5), in_hm(7,8), in_hm(8,0), in_hm(9,2), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,5), out_hm(4,6), out_hm(5,6), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,2), out_hm(8,7), out_hm(9,1), out_hm(9,3), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,6), in_hm(2,7), in_hm(3,9), in_hm(4,2), in_hm(5,4), in_hm(6,5), in_hm(7,8), in_hm(8,0), in_hm(9,1), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,2), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,6), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,2), out_hm(8,7), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,6), in_hm(2,8), in_hm(3,1), in_hm(4,2), in_hm(5,4), in_hm(6,9), in_hm(7,0), in_hm(8,7), in_hm(9,5), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,6), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,5), out_hm(7,2), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,6), in_hm(2,8), in_hm(3,1), in_hm(4,2), in_hm(5,9), in_hm(6,5), in_hm(7,0), in_hm(8,7), in_hm(9,4), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,6), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,2), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,6), in_hm(2,8), in_hm(3,1), in_hm(4,5), in_hm(5,9), in_hm(6,4), in_hm(7,0), in_hm(8,7), in_hm(9,2), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,6), out_hm(6,1), out_hm(6,5), out_hm(6,9), out_hm(7,2), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,3), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,6), in_hm(2,8), in_hm(3,1), in_hm(4,9), in_hm(5,4), in_hm(6,5), in_hm(7,0), in_hm(8,7), in_hm(9,2), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,5), out_hm(4,6), out_hm(5,6), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,2), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,3), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,6), in_hm(2,8), in_hm(3,9), in_hm(4,2), in_hm(5,4), in_hm(6,5), in_hm(7,0), in_hm(8,7), in_hm(9,1), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,2), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,6), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,2), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,9), in_hm(2,7), in_hm(3,1), in_hm(4,2), in_hm(5,4), in_hm(6,5), in_hm(7,8), in_hm(8,0), in_hm(9,6), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,6), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,2), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,5), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,9), in_hm(2,7), in_hm(3,1), in_hm(4,2), in_hm(5,6), in_hm(6,4), in_hm(7,8), in_hm(8,0), in_hm(9,5), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,1), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,2), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,9), in_hm(2,8), in_hm(3,1), in_hm(4,2), in_hm(5,4), in_hm(6,5), in_hm(7,0), in_hm(8,7), in_hm(9,6), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,6), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,2), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,5), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,3), in_hm(1,9), in_hm(2,8), in_hm(3,1), in_hm(4,2), in_hm(5,6), in_hm(6,4), in_hm(7,0), in_hm(8,7), in_hm(9,5), out_hm(0,1), out_hm(0,2), out_hm(0,7), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,5), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,1), out_hm(6,5), out_hm(6,9), out_hm(7,2), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,7), in_hm(1,0), in_hm(2,3), in_hm(3,9), in_hm(4,5), in_hm(5,6), in_hm(6,1), in_hm(7,8), in_hm(8,2), in_hm(9,4), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,8), out_hm(1,3), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,4), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,2), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,0), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,7), in_hm(1,0), in_hm(2,3), in_hm(3,9), in_hm(4,6), in_hm(5,4), in_hm(6,1), in_hm(7,8), in_hm(8,2), in_hm(9,5), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,8), out_hm(1,3), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,4), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,2), out_hm(4,2), out_hm(4,5), out_hm(4,9), out_hm(5,6), out_hm(5,9), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,0), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,7), in_hm(1,0), in_hm(2,4), in_hm(3,1), in_hm(4,5), in_hm(5,6), in_hm(6,9), in_hm(7,8), in_hm(8,2), in_hm(9,3), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,8), out_hm(1,3), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,5), out_hm(7,0), out_hm(7,2), out_hm(8,0), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,7), in_hm(1,0), in_hm(2,4), in_hm(3,1), in_hm(4,6), in_hm(5,9), in_hm(6,5), in_hm(7,8), in_hm(8,2), in_hm(9,3), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,8), out_hm(1,3), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,5), out_hm(4,9), out_hm(5,4), out_hm(5,6), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,0), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,7), in_hm(1,3), in_hm(2,4), in_hm(3,0), in_hm(4,5), in_hm(5,6), in_hm(6,9), in_hm(7,8), in_hm(8,2), in_hm(9,1), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,8), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,5), out_hm(7,0), out_hm(7,2), out_hm(8,0), out_hm(8,7), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,7), in_hm(1,3), in_hm(2,4), in_hm(3,0), in_hm(4,5), in_hm(5,9), in_hm(6,1), in_hm(7,8), in_hm(8,2), in_hm(9,6), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,8), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,6), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,0), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,5), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,7), in_hm(1,3), in_hm(2,4), in_hm(3,0), in_hm(4,6), in_hm(5,9), in_hm(6,5), in_hm(7,8), in_hm(8,2), in_hm(9,1), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,8), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,5), out_hm(4,9), out_hm(5,4), out_hm(5,6), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,0), out_hm(8,7), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,7), in_hm(1,3), in_hm(2,4), in_hm(3,0), in_hm(4,9), in_hm(5,6), in_hm(6,1), in_hm(7,8), in_hm(8,2), in_hm(9,5), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,8), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,5), out_hm(4,6), out_hm(5,4), out_hm(5,9), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,0), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,7), in_hm(1,3), in_hm(2,9), in_hm(3,0), in_hm(4,5), in_hm(5,6), in_hm(6,1), in_hm(7,8), in_hm(8,2), in_hm(9,4), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,8), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,8), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,0), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,7), in_hm(1,3), in_hm(2,9), in_hm(3,0), in_hm(4,6), in_hm(5,4), in_hm(6,1), in_hm(7,8), in_hm(8,2), in_hm(9,5), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,8), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,8), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,5), out_hm(4,9), out_hm(5,6), out_hm(5,9), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,0), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,7), in_hm(1,9), in_hm(2,4), in_hm(3,0), in_hm(4,5), in_hm(5,6), in_hm(6,1), in_hm(7,8), in_hm(8,2), in_hm(9,3), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,8), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,2), out_hm(8,0), out_hm(8,7), out_hm(9,1), out_hm(9,2), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,8), in_hm(1,0), in_hm(2,3), in_hm(3,9), in_hm(4,5), in_hm(5,6), in_hm(6,1), in_hm(7,2), in_hm(8,7), in_hm(9,4), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(1,3), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,4), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,2), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,8), in_hm(1,0), in_hm(2,3), in_hm(3,9), in_hm(4,6), in_hm(5,4), in_hm(6,1), in_hm(7,2), in_hm(8,7), in_hm(9,5), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(1,3), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,4), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,1), out_hm(3,2), out_hm(4,2), out_hm(4,5), out_hm(4,9), out_hm(5,6), out_hm(5,9), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,8), in_hm(1,0), in_hm(2,4), in_hm(3,1), in_hm(4,5), in_hm(5,6), in_hm(6,9), in_hm(7,2), in_hm(8,7), in_hm(9,3), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(1,3), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,5), out_hm(7,0), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,8), in_hm(1,0), in_hm(2,4), in_hm(3,1), in_hm(4,6), in_hm(5,9), in_hm(6,5), in_hm(7,2), in_hm(8,7), in_hm(9,3), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(1,3), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,0), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,5), out_hm(4,9), out_hm(5,4), out_hm(5,6), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,0), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,8), in_hm(1,3), in_hm(2,4), in_hm(3,0), in_hm(4,5), in_hm(5,6), in_hm(6,9), in_hm(7,2), in_hm(8,7), in_hm(9,1), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,5), out_hm(7,0), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,8), in_hm(1,3), in_hm(2,4), in_hm(3,0), in_hm(4,5), in_hm(5,9), in_hm(6,1), in_hm(7,2), in_hm(8,7), in_hm(9,6), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,6), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,5), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,8), in_hm(1,3), in_hm(2,4), in_hm(3,0), in_hm(4,6), in_hm(5,9), in_hm(6,5), in_hm(7,2), in_hm(8,7), in_hm(9,1), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,5), out_hm(4,9), out_hm(5,4), out_hm(5,6), out_hm(6,1), out_hm(6,4), out_hm(6,9), out_hm(7,0), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,8), in_hm(1,3), in_hm(2,4), in_hm(3,0), in_hm(4,9), in_hm(5,6), in_hm(6,1), in_hm(7,2), in_hm(8,7), in_hm(9,5), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,5), out_hm(4,6), out_hm(5,4), out_hm(5,9), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,8), in_hm(1,3), in_hm(2,9), in_hm(3,0), in_hm(4,5), in_hm(5,6), in_hm(6,1), in_hm(7,2), in_hm(8,7), in_hm(9,4), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,8), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,8), in_hm(1,3), in_hm(2,9), in_hm(3,0), in_hm(4,6), in_hm(5,4), in_hm(6,1), in_hm(7,2), in_hm(8,7), in_hm(9,5), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(1,0), out_hm(1,6), out_hm(1,9), out_hm(2,0), out_hm(2,3), out_hm(2,4), out_hm(2,7), out_hm(2,8), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,5), out_hm(4,9), out_hm(5,6), out_hm(5,9), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,3), out_hm(9,4), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,2), arc(0,3), arc(0,7), arc(0,8), arc(1,0), arc(1,3), arc(1,6), arc(1,9), arc(2,0), arc(2,3), arc(2,4), arc(2,7), arc(2,8), arc(2,9), arc(3,0), arc(3,1), arc(3,2), arc(3,9), arc(4,2), arc(4,5), arc(4,6), arc(4,9), arc(5,4), arc(5,6), arc(5,9), arc(6,1), arc(6,4), arc(6,5), arc(6,9), arc(7,0), arc(7,2), arc(7,8), arc(8,0), arc(8,2), arc(8,7), arc(9,1), arc(9,2), arc(9,3), arc(9,4), arc(9,5), arc(9,6), in_hm(0,8), in_hm(1,9), in_hm(2,4), in_hm(3,0), in_hm(4,5), in_hm(5,6), in_hm(6,1), in_hm(7,2), in_hm(8,7), in_hm(9,3), out_hm(0,1), out_hm(0,2), out_hm(0,3), out_hm(0,7), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,0), out_hm(2,3), out_hm(2,7), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(3,2), out_hm(3,9), out_hm(4,2), out_hm(4,6), out_hm(4,9), out_hm(5,4), out_hm(5,9), out_hm(6,4), out_hm(6,5), out_hm(6,9), out_hm(7,0), out_hm(7,8), out_hm(8,0), out_hm(8,2), out_hm(9,1), out_hm(9,2), out_hm(9,4), out_hm(9,5), out_hm(9,6), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
"""
