input = """
% Instantiation generated by
% DLV [build BEN/Oct 14 2010   gcc 4.4.3]

% EDB facts:
start(1).
arc(0,1).
arc(0,4).
arc(0,7).
arc(0,9).
arc(1,0).
arc(1,3).
arc(1,4).
arc(1,6).
arc(2,5).
arc(2,8).
arc(2,9).
arc(3,1).
arc(3,6).
arc(4,0).
arc(4,1).
arc(4,6).
arc(4,7).
arc(5,2).
arc(5,7).
arc(5,8).
arc(5,9).
arc(6,1).
arc(6,3).
arc(6,4).
arc(6,7).
arc(6,8).
arc(7,0).
arc(7,4).
arc(7,5).
arc(7,6).
arc(7,8).
arc(7,9).
arc(8,2).
arc(8,5).
arc(8,6).
arc(8,7).
arc(9,0).
arc(9,2).
arc(9,5).
arc(9,7).
vertex(0).
vertex(1).
vertex(2).
vertex(3).
vertex(4).
vertex(5).
vertex(6).
vertex(7).
vertex(8).
vertex(9).
% Residual ground instantiation of the program:
in_hm(0,1) v out_hm(0,1).
in_hm(0,4) v out_hm(0,4).
in_hm(0,7) v out_hm(0,7).
in_hm(0,9) v out_hm(0,9).
in_hm(1,0) v out_hm(1,0).
in_hm(1,3) v out_hm(1,3).
in_hm(1,4) v out_hm(1,4).
in_hm(1,6) v out_hm(1,6).
in_hm(2,5) v out_hm(2,5).
in_hm(2,8) v out_hm(2,8).
in_hm(2,9) v out_hm(2,9).
in_hm(3,1) v out_hm(3,1).
in_hm(3,6) v out_hm(3,6).
in_hm(4,0) v out_hm(4,0).
in_hm(4,1) v out_hm(4,1).
in_hm(4,6) v out_hm(4,6).
in_hm(4,7) v out_hm(4,7).
in_hm(5,2) v out_hm(5,2).
in_hm(5,7) v out_hm(5,7).
in_hm(5,8) v out_hm(5,8).
in_hm(5,9) v out_hm(5,9).
in_hm(6,1) v out_hm(6,1).
in_hm(6,3) v out_hm(6,3).
in_hm(6,4) v out_hm(6,4).
in_hm(6,7) v out_hm(6,7).
in_hm(6,8) v out_hm(6,8).
in_hm(7,0) v out_hm(7,0).
in_hm(7,4) v out_hm(7,4).
in_hm(7,5) v out_hm(7,5).
in_hm(7,6) v out_hm(7,6).
in_hm(7,8) v out_hm(7,8).
in_hm(7,9) v out_hm(7,9).
in_hm(8,2) v out_hm(8,2).
in_hm(8,5) v out_hm(8,5).
in_hm(8,6) v out_hm(8,6).
in_hm(8,7) v out_hm(8,7).
in_hm(9,0) v out_hm(9,0).
in_hm(9,2) v out_hm(9,2).
in_hm(9,5) v out_hm(9,5).
in_hm(9,7) v out_hm(9,7).
reached(0) :- in_hm(1,0).
reached(6) :- in_hm(1,6).
reached(4) :- in_hm(1,4).
reached(3) :- in_hm(1,3).
reached(1) :- reached(0), in_hm(0,1).
reached(9) :- reached(0), in_hm(0,9).
reached(7) :- reached(0), in_hm(0,7).
reached(4) :- reached(0), in_hm(0,4).
reached(6) :- reached(3), in_hm(3,6).
reached(1) :- reached(3), in_hm(3,1).
reached(1) :- reached(4), in_hm(4,1).
reached(6) :- reached(4), in_hm(4,6).
reached(7) :- reached(4), in_hm(4,7).
reached(0) :- reached(4), in_hm(4,0).
reached(3) :- reached(6), in_hm(6,3).
reached(8) :- reached(6), in_hm(6,8).
reached(7) :- reached(6), in_hm(6,7).
reached(4) :- reached(6), in_hm(6,4).
reached(1) :- reached(6), in_hm(6,1).
reached(0) :- reached(1), in_hm(1,0).
reached(6) :- reached(1), in_hm(1,6).
reached(4) :- reached(1), in_hm(1,4).
reached(3) :- reached(1), in_hm(1,3).
reached(0) :- reached(7), in_hm(7,0).
reached(9) :- reached(7), in_hm(7,9).
reached(8) :- reached(7), in_hm(7,8).
reached(6) :- reached(7), in_hm(7,6).
reached(5) :- reached(7), in_hm(7,5).
reached(4) :- reached(7), in_hm(7,4).
reached(2) :- reached(8), in_hm(8,2).
reached(7) :- reached(8), in_hm(8,7).
reached(6) :- reached(8), in_hm(8,6).
reached(5) :- reached(8), in_hm(8,5).
reached(0) :- reached(9), in_hm(9,0).
reached(7) :- reached(9), in_hm(9,7).
reached(5) :- reached(9), in_hm(9,5).
reached(2) :- reached(9), in_hm(9,2).
reached(5) :- reached(2), in_hm(2,5).
reached(9) :- reached(2), in_hm(2,9).
reached(8) :- reached(2), in_hm(2,8).
reached(7) :- reached(5), in_hm(5,7).
reached(8) :- reached(5), in_hm(5,8).
reached(9) :- reached(5), in_hm(5,9).
reached(2) :- reached(5), in_hm(5,2).
:- in_hm(0,9), in_hm(0,1).
:- in_hm(0,7), in_hm(0,1).
:- in_hm(0,4), in_hm(0,1).
:- in_hm(0,1), in_hm(0,4).
:- in_hm(0,9), in_hm(0,4).
:- in_hm(0,7), in_hm(0,4).
:- in_hm(0,1), in_hm(0,7).
:- in_hm(0,9), in_hm(0,7).
:- in_hm(0,4), in_hm(0,7).
:- in_hm(0,1), in_hm(0,9).
:- in_hm(0,7), in_hm(0,9).
:- in_hm(0,4), in_hm(0,9).
:- in_hm(1,6), in_hm(1,0).
:- in_hm(1,4), in_hm(1,0).
:- in_hm(1,3), in_hm(1,0).
:- in_hm(1,0), in_hm(1,3).
:- in_hm(1,6), in_hm(1,3).
:- in_hm(1,4), in_hm(1,3).
:- in_hm(1,0), in_hm(1,4).
:- in_hm(1,6), in_hm(1,4).
:- in_hm(1,3), in_hm(1,4).
:- in_hm(1,0), in_hm(1,6).
:- in_hm(1,4), in_hm(1,6).
:- in_hm(1,3), in_hm(1,6).
:- in_hm(2,9), in_hm(2,5).
:- in_hm(2,8), in_hm(2,5).
:- in_hm(2,5), in_hm(2,8).
:- in_hm(2,9), in_hm(2,8).
:- in_hm(2,5), in_hm(2,9).
:- in_hm(2,8), in_hm(2,9).
:- in_hm(3,6), in_hm(3,1).
:- in_hm(3,1), in_hm(3,6).
:- in_hm(4,1), in_hm(4,0).
:- in_hm(4,6), in_hm(4,0).
:- in_hm(4,7), in_hm(4,0).
:- in_hm(4,6), in_hm(4,1).
:- in_hm(4,7), in_hm(4,1).
:- in_hm(4,0), in_hm(4,1).
:- in_hm(4,1), in_hm(4,6).
:- in_hm(4,7), in_hm(4,6).
:- in_hm(4,0), in_hm(4,6).
:- in_hm(4,1), in_hm(4,7).
:- in_hm(4,6), in_hm(4,7).
:- in_hm(4,0), in_hm(4,7).
:- in_hm(5,7), in_hm(5,2).
:- in_hm(5,8), in_hm(5,2).
:- in_hm(5,9), in_hm(5,2).
:- in_hm(5,8), in_hm(5,7).
:- in_hm(5,9), in_hm(5,7).
:- in_hm(5,2), in_hm(5,7).
:- in_hm(5,7), in_hm(5,8).
:- in_hm(5,9), in_hm(5,8).
:- in_hm(5,2), in_hm(5,8).
:- in_hm(5,7), in_hm(5,9).
:- in_hm(5,8), in_hm(5,9).
:- in_hm(5,2), in_hm(5,9).
:- in_hm(6,3), in_hm(6,1).
:- in_hm(6,8), in_hm(6,1).
:- in_hm(6,7), in_hm(6,1).
:- in_hm(6,4), in_hm(6,1).
:- in_hm(6,8), in_hm(6,3).
:- in_hm(6,7), in_hm(6,3).
:- in_hm(6,4), in_hm(6,3).
:- in_hm(6,1), in_hm(6,3).
:- in_hm(6,3), in_hm(6,4).
:- in_hm(6,8), in_hm(6,4).
:- in_hm(6,7), in_hm(6,4).
:- in_hm(6,1), in_hm(6,4).
:- in_hm(6,3), in_hm(6,7).
:- in_hm(6,8), in_hm(6,7).
:- in_hm(6,4), in_hm(6,7).
:- in_hm(6,1), in_hm(6,7).
:- in_hm(6,3), in_hm(6,8).
:- in_hm(6,7), in_hm(6,8).
:- in_hm(6,4), in_hm(6,8).
:- in_hm(6,1), in_hm(6,8).
:- in_hm(7,9), in_hm(7,0).
:- in_hm(7,8), in_hm(7,0).
:- in_hm(7,6), in_hm(7,0).
:- in_hm(7,5), in_hm(7,0).
:- in_hm(7,4), in_hm(7,0).
:- in_hm(7,0), in_hm(7,4).
:- in_hm(7,9), in_hm(7,4).
:- in_hm(7,8), in_hm(7,4).
:- in_hm(7,6), in_hm(7,4).
:- in_hm(7,5), in_hm(7,4).
:- in_hm(7,0), in_hm(7,5).
:- in_hm(7,9), in_hm(7,5).
:- in_hm(7,8), in_hm(7,5).
:- in_hm(7,6), in_hm(7,5).
:- in_hm(7,4), in_hm(7,5).
:- in_hm(7,0), in_hm(7,6).
:- in_hm(7,9), in_hm(7,6).
:- in_hm(7,8), in_hm(7,6).
:- in_hm(7,5), in_hm(7,6).
:- in_hm(7,4), in_hm(7,6).
:- in_hm(7,0), in_hm(7,8).
:- in_hm(7,9), in_hm(7,8).
:- in_hm(7,6), in_hm(7,8).
:- in_hm(7,5), in_hm(7,8).
:- in_hm(7,4), in_hm(7,8).
:- in_hm(7,0), in_hm(7,9).
:- in_hm(7,8), in_hm(7,9).
:- in_hm(7,6), in_hm(7,9).
:- in_hm(7,5), in_hm(7,9).
:- in_hm(7,4), in_hm(7,9).
:- in_hm(8,7), in_hm(8,2).
:- in_hm(8,6), in_hm(8,2).
:- in_hm(8,5), in_hm(8,2).
:- in_hm(8,2), in_hm(8,5).
:- in_hm(8,7), in_hm(8,5).
:- in_hm(8,6), in_hm(8,5).
:- in_hm(8,2), in_hm(8,6).
:- in_hm(8,7), in_hm(8,6).
:- in_hm(8,5), in_hm(8,6).
:- in_hm(8,2), in_hm(8,7).
:- in_hm(8,6), in_hm(8,7).
:- in_hm(8,5), in_hm(8,7).
:- in_hm(9,7), in_hm(9,0).
:- in_hm(9,5), in_hm(9,0).
:- in_hm(9,2), in_hm(9,0).
:- in_hm(9,0), in_hm(9,2).
:- in_hm(9,7), in_hm(9,2).
:- in_hm(9,5), in_hm(9,2).
:- in_hm(9,0), in_hm(9,5).
:- in_hm(9,7), in_hm(9,5).
:- in_hm(9,2), in_hm(9,5).
:- in_hm(9,0), in_hm(9,7).
:- in_hm(9,5), in_hm(9,7).
:- in_hm(9,2), in_hm(9,7).
:- in_hm(3,1), in_hm(0,1).
:- in_hm(4,1), in_hm(0,1).
:- in_hm(6,1), in_hm(0,1).
:- in_hm(7,4), in_hm(0,4).
:- in_hm(6,4), in_hm(0,4).
:- in_hm(1,4), in_hm(0,4).
:- in_hm(4,7), in_hm(0,7).
:- in_hm(9,7), in_hm(0,7).
:- in_hm(8,7), in_hm(0,7).
:- in_hm(6,7), in_hm(0,7).
:- in_hm(5,7), in_hm(0,7).
:- in_hm(7,9), in_hm(0,9).
:- in_hm(5,9), in_hm(0,9).
:- in_hm(2,9), in_hm(0,9).
:- in_hm(4,0), in_hm(1,0).
:- in_hm(9,0), in_hm(1,0).
:- in_hm(7,0), in_hm(1,0).
:- in_hm(6,3), in_hm(1,3).
:- in_hm(0,4), in_hm(1,4).
:- in_hm(7,4), in_hm(1,4).
:- in_hm(6,4), in_hm(1,4).
:- in_hm(3,6), in_hm(1,6).
:- in_hm(8,6), in_hm(1,6).
:- in_hm(7,6), in_hm(1,6).
:- in_hm(4,6), in_hm(1,6).
:- in_hm(9,5), in_hm(2,5).
:- in_hm(8,5), in_hm(2,5).
:- in_hm(7,5), in_hm(2,5).
:- in_hm(5,8), in_hm(2,8).
:- in_hm(7,8), in_hm(2,8).
:- in_hm(6,8), in_hm(2,8).
:- in_hm(0,9), in_hm(2,9).
:- in_hm(7,9), in_hm(2,9).
:- in_hm(5,9), in_hm(2,9).
:- in_hm(4,1), in_hm(3,1).
:- in_hm(6,1), in_hm(3,1).
:- in_hm(0,1), in_hm(3,1).
:- in_hm(8,6), in_hm(3,6).
:- in_hm(7,6), in_hm(3,6).
:- in_hm(4,6), in_hm(3,6).
:- in_hm(1,6), in_hm(3,6).
:- in_hm(9,0), in_hm(4,0).
:- in_hm(7,0), in_hm(4,0).
:- in_hm(1,0), in_hm(4,0).
:- in_hm(3,1), in_hm(4,1).
:- in_hm(6,1), in_hm(4,1).
:- in_hm(0,1), in_hm(4,1).
:- in_hm(3,6), in_hm(4,6).
:- in_hm(8,6), in_hm(4,6).
:- in_hm(7,6), in_hm(4,6).
:- in_hm(1,6), in_hm(4,6).
:- in_hm(9,7), in_hm(4,7).
:- in_hm(8,7), in_hm(4,7).
:- in_hm(6,7), in_hm(4,7).
:- in_hm(5,7), in_hm(4,7).
:- in_hm(0,7), in_hm(4,7).
:- in_hm(9,2), in_hm(5,2).
:- in_hm(8,2), in_hm(5,2).
:- in_hm(4,7), in_hm(5,7).
:- in_hm(9,7), in_hm(5,7).
:- in_hm(8,7), in_hm(5,7).
:- in_hm(6,7), in_hm(5,7).
:- in_hm(0,7), in_hm(5,7).
:- in_hm(7,8), in_hm(5,8).
:- in_hm(6,8), in_hm(5,8).
:- in_hm(2,8), in_hm(5,8).
:- in_hm(0,9), in_hm(5,9).
:- in_hm(7,9), in_hm(5,9).
:- in_hm(2,9), in_hm(5,9).
:- in_hm(3,1), in_hm(6,1).
:- in_hm(4,1), in_hm(6,1).
:- in_hm(0,1), in_hm(6,1).
:- in_hm(1,3), in_hm(6,3).
:- in_hm(0,4), in_hm(6,4).
:- in_hm(7,4), in_hm(6,4).
:- in_hm(1,4), in_hm(6,4).
:- in_hm(4,7), in_hm(6,7).
:- in_hm(9,7), in_hm(6,7).
:- in_hm(8,7), in_hm(6,7).
:- in_hm(5,7), in_hm(6,7).
:- in_hm(0,7), in_hm(6,7).
:- in_hm(5,8), in_hm(6,8).
:- in_hm(7,8), in_hm(6,8).
:- in_hm(2,8), in_hm(6,8).
:- in_hm(4,0), in_hm(7,0).
:- in_hm(9,0), in_hm(7,0).
:- in_hm(1,0), in_hm(7,0).
:- in_hm(0,4), in_hm(7,4).
:- in_hm(6,4), in_hm(7,4).
:- in_hm(1,4), in_hm(7,4).
:- in_hm(2,5), in_hm(7,5).
:- in_hm(9,5), in_hm(7,5).
:- in_hm(8,5), in_hm(7,5).
:- in_hm(3,6), in_hm(7,6).
:- in_hm(8,6), in_hm(7,6).
:- in_hm(4,6), in_hm(7,6).
:- in_hm(1,6), in_hm(7,6).
:- in_hm(5,8), in_hm(7,8).
:- in_hm(6,8), in_hm(7,8).
:- in_hm(2,8), in_hm(7,8).
:- in_hm(0,9), in_hm(7,9).
:- in_hm(5,9), in_hm(7,9).
:- in_hm(2,9), in_hm(7,9).
:- in_hm(5,2), in_hm(8,2).
:- in_hm(9,2), in_hm(8,2).
:- in_hm(2,5), in_hm(8,5).
:- in_hm(9,5), in_hm(8,5).
:- in_hm(7,5), in_hm(8,5).
:- in_hm(3,6), in_hm(8,6).
:- in_hm(7,6), in_hm(8,6).
:- in_hm(4,6), in_hm(8,6).
:- in_hm(1,6), in_hm(8,6).
:- in_hm(4,7), in_hm(8,7).
:- in_hm(9,7), in_hm(8,7).
:- in_hm(6,7), in_hm(8,7).
:- in_hm(5,7), in_hm(8,7).
:- in_hm(0,7), in_hm(8,7).
:- in_hm(4,0), in_hm(9,0).
:- in_hm(7,0), in_hm(9,0).
:- in_hm(1,0), in_hm(9,0).
:- in_hm(5,2), in_hm(9,2).
:- in_hm(8,2), in_hm(9,2).
:- in_hm(2,5), in_hm(9,5).
:- in_hm(8,5), in_hm(9,5).
:- in_hm(7,5), in_hm(9,5).
:- in_hm(4,7), in_hm(9,7).
:- in_hm(8,7), in_hm(9,7).
:- in_hm(6,7), in_hm(9,7).
:- in_hm(5,7), in_hm(9,7).
:- in_hm(0,7), in_hm(9,7).
:- not reached(0).
:- not reached(0).
:- not reached(0).
:- not reached(0).
:- not reached(1).
:- not reached(1).
:- not reached(1).
:- not reached(1).
:- not reached(2).
:- not reached(2).
:- not reached(2).
:- not reached(3).
:- not reached(3).
:- not reached(4).
:- not reached(4).
:- not reached(4).
:- not reached(4).
:- not reached(5).
:- not reached(5).
:- not reached(5).
:- not reached(5).
:- not reached(6).
:- not reached(6).
:- not reached(6).
:- not reached(6).
:- not reached(6).
:- not reached(7).
:- not reached(7).
:- not reached(7).
:- not reached(7).
:- not reached(7).
:- not reached(7).
:- not reached(8).
:- not reached(8).
:- not reached(8).
:- not reached(8).
:- not reached(9).
:- not reached(9).
:- not reached(9).
:- not reached(9).

"""

output = """
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,1), in_hm(1,3), in_hm(2,5), in_hm(3,6), in_hm(4,0), in_hm(5,9), in_hm(6,8), in_hm(7,4), in_hm(8,2), in_hm(9,7), out_hm(0,4), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(4,1), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,7), out_hm(5,8), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,7), out_hm(7,0), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,5), out_hm(8,6), out_hm(8,7), out_hm(9,0), out_hm(9,2), out_hm(9,5), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,1), in_hm(1,3), in_hm(2,5), in_hm(3,6), in_hm(4,7), in_hm(5,9), in_hm(6,4), in_hm(7,8), in_hm(8,2), in_hm(9,0), out_hm(0,4), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(4,0), out_hm(4,1), out_hm(4,6), out_hm(5,2), out_hm(5,7), out_hm(5,8), out_hm(6,1), out_hm(6,3), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,9), out_hm(8,5), out_hm(8,6), out_hm(8,7), out_hm(9,2), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,1), in_hm(1,3), in_hm(2,9), in_hm(3,6), in_hm(4,0), in_hm(5,2), in_hm(6,8), in_hm(7,4), in_hm(8,5), in_hm(9,7), out_hm(0,4), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,8), out_hm(3,1), out_hm(4,1), out_hm(4,6), out_hm(4,7), out_hm(5,7), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,7), out_hm(7,0), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,6), out_hm(8,7), out_hm(9,0), out_hm(9,2), out_hm(9,5), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,1), in_hm(1,3), in_hm(2,9), in_hm(3,6), in_hm(4,0), in_hm(5,7), in_hm(6,8), in_hm(7,4), in_hm(8,2), in_hm(9,5), out_hm(0,4), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,8), out_hm(3,1), out_hm(4,1), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,7), out_hm(7,0), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,5), out_hm(8,6), out_hm(8,7), out_hm(9,0), out_hm(9,2), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,1), in_hm(1,3), in_hm(2,9), in_hm(3,6), in_hm(4,7), in_hm(5,2), in_hm(6,4), in_hm(7,8), in_hm(8,5), in_hm(9,0), out_hm(0,4), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,8), out_hm(3,1), out_hm(4,0), out_hm(4,1), out_hm(4,6), out_hm(5,7), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,3), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,9), out_hm(8,2), out_hm(8,6), out_hm(8,7), out_hm(9,2), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,1), in_hm(1,3), in_hm(2,9), in_hm(3,6), in_hm(4,7), in_hm(5,8), in_hm(6,4), in_hm(7,5), in_hm(8,2), in_hm(9,0), out_hm(0,4), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,8), out_hm(3,1), out_hm(4,0), out_hm(4,1), out_hm(4,6), out_hm(5,2), out_hm(5,7), out_hm(5,9), out_hm(6,1), out_hm(6,3), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,5), out_hm(8,6), out_hm(8,7), out_hm(9,2), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,4), in_hm(1,0), in_hm(2,5), in_hm(3,1), in_hm(4,7), in_hm(5,8), in_hm(6,3), in_hm(7,9), in_hm(8,6), in_hm(9,2), out_hm(0,1), out_hm(0,7), out_hm(0,9), out_hm(1,3), out_hm(1,4), out_hm(1,6), out_hm(2,8), out_hm(2,9), out_hm(3,6), out_hm(4,0), out_hm(4,1), out_hm(4,6), out_hm(5,2), out_hm(5,7), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(8,2), out_hm(8,5), out_hm(8,7), out_hm(9,0), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,4), in_hm(1,0), in_hm(2,8), in_hm(3,1), in_hm(4,7), in_hm(5,2), in_hm(6,3), in_hm(7,9), in_hm(8,6), in_hm(9,5), out_hm(0,1), out_hm(0,7), out_hm(0,9), out_hm(1,3), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,9), out_hm(3,6), out_hm(4,0), out_hm(4,1), out_hm(4,6), out_hm(5,7), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(8,2), out_hm(8,5), out_hm(8,7), out_hm(9,0), out_hm(9,2), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,4), in_hm(1,0), in_hm(2,8), in_hm(3,1), in_hm(4,7), in_hm(5,9), in_hm(6,3), in_hm(7,5), in_hm(8,6), in_hm(9,2), out_hm(0,1), out_hm(0,7), out_hm(0,9), out_hm(1,3), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,9), out_hm(3,6), out_hm(4,0), out_hm(4,1), out_hm(4,6), out_hm(5,2), out_hm(5,7), out_hm(5,8), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,5), out_hm(8,7), out_hm(9,0), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,4), in_hm(1,3), in_hm(2,5), in_hm(3,6), in_hm(4,1), in_hm(5,7), in_hm(6,8), in_hm(7,9), in_hm(8,2), in_hm(9,0), out_hm(0,1), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(4,0), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,7), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(8,5), out_hm(8,6), out_hm(8,7), out_hm(9,2), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,4), in_hm(1,3), in_hm(2,5), in_hm(3,6), in_hm(4,1), in_hm(5,9), in_hm(6,7), in_hm(7,8), in_hm(8,2), in_hm(9,0), out_hm(0,1), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(4,0), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,7), out_hm(5,8), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,9), out_hm(8,5), out_hm(8,6), out_hm(8,7), out_hm(9,2), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,4), in_hm(1,3), in_hm(2,5), in_hm(3,6), in_hm(4,1), in_hm(5,9), in_hm(6,8), in_hm(7,0), in_hm(8,2), in_hm(9,7), out_hm(0,1), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(4,0), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,7), out_hm(5,8), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,7), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,5), out_hm(8,6), out_hm(8,7), out_hm(9,0), out_hm(9,2), out_hm(9,5), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,4), in_hm(1,3), in_hm(2,9), in_hm(3,6), in_hm(4,1), in_hm(5,2), in_hm(6,7), in_hm(7,8), in_hm(8,5), in_hm(9,0), out_hm(0,1), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,8), out_hm(3,1), out_hm(4,0), out_hm(4,6), out_hm(4,7), out_hm(5,7), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,9), out_hm(8,2), out_hm(8,6), out_hm(8,7), out_hm(9,2), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,4), in_hm(1,3), in_hm(2,9), in_hm(3,6), in_hm(4,1), in_hm(5,2), in_hm(6,8), in_hm(7,0), in_hm(8,5), in_hm(9,7), out_hm(0,1), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,8), out_hm(3,1), out_hm(4,0), out_hm(4,6), out_hm(4,7), out_hm(5,7), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,7), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,6), out_hm(8,7), out_hm(9,0), out_hm(9,2), out_hm(9,5), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,4), in_hm(1,3), in_hm(2,9), in_hm(3,6), in_hm(4,1), in_hm(5,2), in_hm(6,8), in_hm(7,5), in_hm(8,7), in_hm(9,0), out_hm(0,1), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,8), out_hm(3,1), out_hm(4,0), out_hm(4,6), out_hm(4,7), out_hm(5,7), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,7), out_hm(7,0), out_hm(7,4), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,5), out_hm(8,6), out_hm(9,2), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,4), in_hm(1,3), in_hm(2,9), in_hm(3,6), in_hm(4,1), in_hm(5,7), in_hm(6,8), in_hm(7,0), in_hm(8,2), in_hm(9,5), out_hm(0,1), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,8), out_hm(3,1), out_hm(4,0), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,7), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,5), out_hm(8,6), out_hm(8,7), out_hm(9,0), out_hm(9,2), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,4), in_hm(1,3), in_hm(2,9), in_hm(3,6), in_hm(4,1), in_hm(5,8), in_hm(6,7), in_hm(7,5), in_hm(8,2), in_hm(9,0), out_hm(0,1), out_hm(0,7), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,8), out_hm(3,1), out_hm(4,0), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,7), out_hm(5,9), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,5), out_hm(8,6), out_hm(8,7), out_hm(9,2), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,7), in_hm(1,3), in_hm(2,5), in_hm(3,6), in_hm(4,1), in_hm(5,9), in_hm(6,8), in_hm(7,4), in_hm(8,2), in_hm(9,0), out_hm(0,1), out_hm(0,4), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,8), out_hm(2,9), out_hm(3,1), out_hm(4,0), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,7), out_hm(5,8), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,7), out_hm(7,0), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,5), out_hm(8,6), out_hm(8,7), out_hm(9,2), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,7), in_hm(1,3), in_hm(2,9), in_hm(3,6), in_hm(4,1), in_hm(5,2), in_hm(6,8), in_hm(7,4), in_hm(8,5), in_hm(9,0), out_hm(0,1), out_hm(0,4), out_hm(0,9), out_hm(1,0), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,8), out_hm(3,1), out_hm(4,0), out_hm(4,6), out_hm(4,7), out_hm(5,7), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,3), out_hm(6,4), out_hm(6,7), out_hm(7,0), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,6), out_hm(8,7), out_hm(9,2), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,7), in_hm(1,4), in_hm(2,5), in_hm(3,1), in_hm(4,0), in_hm(5,8), in_hm(6,3), in_hm(7,9), in_hm(8,6), in_hm(9,2), out_hm(0,1), out_hm(0,4), out_hm(0,9), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,8), out_hm(2,9), out_hm(3,6), out_hm(4,1), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,7), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(8,2), out_hm(8,5), out_hm(8,7), out_hm(9,0), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,7), in_hm(1,4), in_hm(2,8), in_hm(3,1), in_hm(4,0), in_hm(5,2), in_hm(6,3), in_hm(7,9), in_hm(8,6), in_hm(9,5), out_hm(0,1), out_hm(0,4), out_hm(0,9), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,5), out_hm(2,9), out_hm(3,6), out_hm(4,1), out_hm(4,6), out_hm(4,7), out_hm(5,7), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(8,2), out_hm(8,5), out_hm(8,7), out_hm(9,0), out_hm(9,2), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,7), in_hm(1,4), in_hm(2,8), in_hm(3,1), in_hm(4,0), in_hm(5,9), in_hm(6,3), in_hm(7,5), in_hm(8,6), in_hm(9,2), out_hm(0,1), out_hm(0,4), out_hm(0,9), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,5), out_hm(2,9), out_hm(3,6), out_hm(4,1), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,7), out_hm(5,8), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,5), out_hm(8,7), out_hm(9,0), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,9), in_hm(1,0), in_hm(2,5), in_hm(3,1), in_hm(4,6), in_hm(5,8), in_hm(6,3), in_hm(7,4), in_hm(8,7), in_hm(9,2), out_hm(0,1), out_hm(0,4), out_hm(0,7), out_hm(1,3), out_hm(1,4), out_hm(1,6), out_hm(2,8), out_hm(2,9), out_hm(3,6), out_hm(4,0), out_hm(4,1), out_hm(4,7), out_hm(5,2), out_hm(5,7), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,5), out_hm(8,6), out_hm(9,0), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,9), in_hm(1,0), in_hm(2,8), in_hm(3,1), in_hm(4,6), in_hm(5,2), in_hm(6,3), in_hm(7,4), in_hm(8,7), in_hm(9,5), out_hm(0,1), out_hm(0,4), out_hm(0,7), out_hm(1,3), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,9), out_hm(3,6), out_hm(4,0), out_hm(4,1), out_hm(4,7), out_hm(5,7), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,5), out_hm(8,6), out_hm(9,0), out_hm(9,2), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,9), in_hm(1,0), in_hm(2,8), in_hm(3,1), in_hm(4,6), in_hm(5,7), in_hm(6,3), in_hm(7,4), in_hm(8,5), in_hm(9,2), out_hm(0,1), out_hm(0,4), out_hm(0,7), out_hm(1,3), out_hm(1,4), out_hm(1,6), out_hm(2,5), out_hm(2,9), out_hm(3,6), out_hm(4,0), out_hm(4,1), out_hm(4,7), out_hm(5,2), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,6), out_hm(8,7), out_hm(9,0), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,9), in_hm(1,4), in_hm(2,5), in_hm(3,1), in_hm(4,0), in_hm(5,7), in_hm(6,3), in_hm(7,8), in_hm(8,6), in_hm(9,2), out_hm(0,1), out_hm(0,4), out_hm(0,7), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,8), out_hm(2,9), out_hm(3,6), out_hm(4,1), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,9), out_hm(8,2), out_hm(8,5), out_hm(8,7), out_hm(9,0), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,9), in_hm(1,4), in_hm(2,5), in_hm(3,1), in_hm(4,0), in_hm(5,8), in_hm(6,3), in_hm(7,6), in_hm(8,7), in_hm(9,2), out_hm(0,1), out_hm(0,4), out_hm(0,7), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,8), out_hm(2,9), out_hm(3,6), out_hm(4,1), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,7), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,5), out_hm(8,6), out_hm(9,0), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,9), in_hm(1,4), in_hm(2,5), in_hm(3,1), in_hm(4,7), in_hm(5,8), in_hm(6,3), in_hm(7,0), in_hm(8,6), in_hm(9,2), out_hm(0,1), out_hm(0,4), out_hm(0,7), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,8), out_hm(2,9), out_hm(3,6), out_hm(4,0), out_hm(4,1), out_hm(4,6), out_hm(5,2), out_hm(5,7), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,5), out_hm(8,7), out_hm(9,0), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,9), in_hm(1,4), in_hm(2,8), in_hm(3,1), in_hm(4,0), in_hm(5,2), in_hm(6,3), in_hm(7,5), in_hm(8,6), in_hm(9,7), out_hm(0,1), out_hm(0,4), out_hm(0,7), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,5), out_hm(2,9), out_hm(3,6), out_hm(4,1), out_hm(4,6), out_hm(4,7), out_hm(5,7), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,5), out_hm(8,7), out_hm(9,0), out_hm(9,2), out_hm(9,5), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,9), in_hm(1,4), in_hm(2,8), in_hm(3,1), in_hm(4,0), in_hm(5,2), in_hm(6,3), in_hm(7,6), in_hm(8,7), in_hm(9,5), out_hm(0,1), out_hm(0,4), out_hm(0,7), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,5), out_hm(2,9), out_hm(3,6), out_hm(4,1), out_hm(4,6), out_hm(4,7), out_hm(5,7), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,5), out_hm(8,6), out_hm(9,0), out_hm(9,2), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,9), in_hm(1,4), in_hm(2,8), in_hm(3,1), in_hm(4,0), in_hm(5,7), in_hm(6,3), in_hm(7,6), in_hm(8,5), in_hm(9,2), out_hm(0,1), out_hm(0,4), out_hm(0,7), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,5), out_hm(2,9), out_hm(3,6), out_hm(4,1), out_hm(4,6), out_hm(4,7), out_hm(5,2), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,0), out_hm(7,4), out_hm(7,5), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,6), out_hm(8,7), out_hm(9,0), out_hm(9,5), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
{arc(0,1), arc(0,4), arc(0,7), arc(0,9), arc(1,0), arc(1,3), arc(1,4), arc(1,6), arc(2,5), arc(2,8), arc(2,9), arc(3,1), arc(3,6), arc(4,0), arc(4,1), arc(4,6), arc(4,7), arc(5,2), arc(5,7), arc(5,8), arc(5,9), arc(6,1), arc(6,3), arc(6,4), arc(6,7), arc(6,8), arc(7,0), arc(7,4), arc(7,5), arc(7,6), arc(7,8), arc(7,9), arc(8,2), arc(8,5), arc(8,6), arc(8,7), arc(9,0), arc(9,2), arc(9,5), arc(9,7), in_hm(0,9), in_hm(1,4), in_hm(2,8), in_hm(3,1), in_hm(4,7), in_hm(5,2), in_hm(6,3), in_hm(7,0), in_hm(8,6), in_hm(9,5), out_hm(0,1), out_hm(0,4), out_hm(0,7), out_hm(1,0), out_hm(1,3), out_hm(1,6), out_hm(2,5), out_hm(2,9), out_hm(3,6), out_hm(4,0), out_hm(4,1), out_hm(4,6), out_hm(5,7), out_hm(5,8), out_hm(5,9), out_hm(6,1), out_hm(6,4), out_hm(6,7), out_hm(6,8), out_hm(7,4), out_hm(7,5), out_hm(7,6), out_hm(7,8), out_hm(7,9), out_hm(8,2), out_hm(8,5), out_hm(8,7), out_hm(9,0), out_hm(9,2), out_hm(9,7), reached(0), reached(1), reached(2), reached(3), reached(4), reached(5), reached(6), reached(7), reached(8), reached(9), start(1), vertex(0), vertex(1), vertex(2), vertex(3), vertex(4), vertex(5), vertex(6), vertex(7), vertex(8), vertex(9)}
"""
