input = """
% Test with overly long identifiers (generated by the rewriting).

f(X,1) :- abcdefghijklmnopqrstuvwxyz(_,_,_,_,_,_,_,_,X),
          g(A), g(B),
          not f(1,X).

f(X,2) :- abcdefghijklmnopqrstuvwxyz(_,_,_,_,_,_,_,X,_),
          g(A), g(B),
          not f(2,X).

abcdefghijklmnopqrstuvwxyz(1,2,3,4,5,6,7,X,X) :- g(X).

f(1,X) :- g(X).

g(x1).
g(x2).

"""

output = """
{abcdefghijklmnopqrstuvwxyz(1,2,3,4,5,6,7,x1,x1), abcdefghijklmnopqrstuvwxyz(1,2,3,4,5,6,7,x2,x2), f(1,x1), f(1,x2), f(x1,2), f(x2,2), g(x1), g(x2)}
"""
